_wandb:
    value:
        cli_version: 0.22.0
        e:
            f2x5dkchxiu460xmq2ckvhl1awswjgks:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "3221225472"
                codePath: Prosit1.ipynb
                codePathLocal: Prosit1.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "323065606144"
                email: innocent.ics.2025@gmail.com
                executable: /Users/innocentchikwanda/miniconda3/envs/d2l/bin/python
                host: Innocents-MacBook-Air.local
                memory:
                    total: "25769803776"
                os: macOS-15.2-arm64-arm-64bit
                program: Prosit1.ipynb
                python: CPython 3.9.21
                root: /Users/innocentchikwanda/Desktop/Grad School/Deep Learning/Prosit1
                startedAt: "2025-09-19T20:56:22.612837Z"
                writerId: f2x5dkchxiu460xmq2ckvhl1awswjgks
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.9.21
            "5": 0.22.0
            "8":
                - 1
            "12": 0.22.0
            "13": darwin-arm64
batch_size:
    value: 64
dropout:
    value: 0.5
epochs:
    value: 20
hidden_sizes:
    value:
        - 2048
        - 1024
        - 512
        - 256
l1_lambda:
    value: 0
lr:
    value: 0.01
model:
    value: FeedForwardMLP
momentum:
    value: 0.9
patience:
    value: 6
weight_decay:
    value: 0
